import { useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Boxes, Database, Pencil, Plus, Trash2 } from "lucide-react"
import { useSearchParams } from "react-router-dom"
import {
  addTemplateActuator, addTemplateSensor, createActuatorModel, createDeviceTemplate, createSensorModel,
  deleteActuatorModel, deleteDeviceTemplate, deleteSensorModel, deleteTemplateActuator, deleteTemplateSensor,
  listActuatorModels, listDeviceTemplates, listSensorModels, queryKeys, updateActuatorModel,
  updateDeviceTemplate, updateSensorModel, updateTemplateActuator, updateTemplateSensor,
} from "@/api/resources"
import type {
  ActuatorModel, ActuatorModelInput, DeviceTemplate, DeviceTemplateInput, SensorModel, SensorModelInput,
  TemplateActuatorSlot, TemplateActuatorSlotInput, TemplateSensorSlot, TemplateSensorSlotInput,
} from "@/api/contracts"
import { errorMessage } from "@/api/client"
import { useAuth } from "@/app/auth"
import {
  AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription,
  AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger,
} from "@/shared/ui/alert-dialog"
import { Button } from "@/shared/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/shared/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/shared/ui/dialog"
import { EmptyState } from "@/shared/ui/empty-state"
import { Input } from "@/shared/ui/input"
import { Label } from "@/shared/ui/label"
import { Skeleton } from "@/shared/ui/skeleton"
import { StatusBadge } from "@/shared/ui/status-badge"
import { Switch } from "@/shared/ui/switch"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/shared/ui/tabs"
import { Textarea } from "@/shared/ui/textarea"

type CatalogTab = "templates" | "sensors" | "actuators"
function isCatalogTab(value: string | null): value is CatalogTab { return value === "templates" || value === "sensors" || value === "actuators" }

export function CatalogsCanonicalPage() {
  const [params, setParams] = useSearchParams()
  const tabParam = params.get("tab")
  const tab: CatalogTab = isCatalogTab(tabParam) ? tabParam : "templates"
  const { can } = useAuth()
  const templates = useQuery({ queryKey: queryKeys.templates, queryFn: listDeviceTemplates })
  const sensors = useQuery({ queryKey: queryKeys.sensorModels, queryFn: listSensorModels })
  const actuators = useQuery({ queryKey: queryKeys.actuatorModels, queryFn: listActuatorModels })

  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Danh mục vận hành</h1><p className="text-sm text-muted-foreground">DeviceTemplate, SensorModel và ActuatorModel là catalog, không phải runtime instance.</p></div><Tabs value={tab} onValueChange={(value) => { if (isCatalogTab(value)) setParams({ tab: value }, { replace: true }) }}><TabsList className="max-w-full overflow-x-auto"><TabsTrigger value="templates">DeviceTemplate</TabsTrigger><TabsTrigger value="sensors">SensorModel</TabsTrigger><TabsTrigger value="actuators">ActuatorModel</TabsTrigger></TabsList><TabsContent value="templates"><TemplateCatalog items={templates.data ?? []} loading={templates.isLoading} error={templates.error} sensorModels={sensors.data ?? []} actuatorModels={actuators.data ?? []} canCreate={can("device_templates.create")} canUpdate={can("device_templates.update")} canDelete={can("device_templates.delete")} /></TabsContent><TabsContent value="sensors"><SensorModelCatalog items={sensors.data ?? []} loading={sensors.isLoading} error={sensors.error} canCreate={can("sensor_models.create")} canUpdate={can("sensor_models.update")} canDelete={can("sensor_models.delete")} /></TabsContent><TabsContent value="actuators"><ActuatorModelCatalog items={actuators.data ?? []} loading={actuators.isLoading} error={actuators.error} canCreate={can("actuator_models.create")} canUpdate={can("actuator_models.update")} canDelete={can("actuator_models.delete")} /></TabsContent></Tabs></div>
}

function TemplateCatalog({ items, loading, error, sensorModels, actuatorModels, canCreate, canUpdate, canDelete }: { items: DeviceTemplate[]; loading: boolean; error: Error | null; sensorModels: SensorModel[]; actuatorModels: ActuatorModel[]; canCreate: boolean; canUpdate: boolean; canDelete: boolean }) {
  const client = useQueryClient()
  const [createOpen, setCreateOpen] = useState(false)
  const [draft, setDraft] = useState<DeviceTemplateInput>({ code: "", name: "", description: null })
  const refresh = () => client.invalidateQueries({ queryKey: queryKeys.templates })
  const creation = useMutation({ mutationFn: () => createDeviceTemplate({ ...draft, code: draft.code.trim().toUpperCase(), name: draft.name.trim(), description: draft.description?.trim() || null }), onSuccess: async () => { await refresh(); setDraft({ code: "", name: "", description: null }); setCreateOpen(false) } })
  if (loading) return <Skeleton className="h-96" />
  if (error) return <EmptyState icon={Boxes} title="Không thể tải DeviceTemplate" description={errorMessage(error)} />
  return <div className="space-y-4">{canCreate ? <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogTrigger asChild><Button><Plus />Thêm DeviceTemplate</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Tạo DeviceTemplate</DialogTitle><DialogDescription>Tạo catalog trước, sau đó cấu hình Sensor và Actuator slot theo protocol order.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); creation.mutate() }}><TemplateFields draft={draft} onChange={setDraft} codeEditable />{creation.isError ? <ErrorText error={creation.error} /> : null}<DialogFooter><Button type="submit" disabled={creation.isPending}>Tạo template</Button></DialogFooter></form></DialogContent></Dialog> : null}{items.length ? <div className="space-y-5">{items.map((template) => <TemplateCard key={template.id} template={template} sensorModels={sensorModels} actuatorModels={actuatorModels} canUpdate={canUpdate} canDelete={canDelete} refresh={refresh} />)}</div> : <EmptyState icon={Boxes} title="Chưa có DeviceTemplate" description="Tạo catalog template trước khi khởi tạo Device." />}</div>
}

function TemplateCard({ template, sensorModels, actuatorModels, canUpdate, canDelete, refresh }: { template: DeviceTemplate; sensorModels: SensorModel[]; actuatorModels: ActuatorModel[]; canUpdate: boolean; canDelete: boolean; refresh: () => Promise<unknown> }) {
  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState<DeviceTemplateInput>({ code: template.code, name: template.name, description: template.description })
  const update = useMutation({ mutationFn: () => updateDeviceTemplate(template.id, { name: draft.name, description: draft.description, is_active: template.is_active }), onSuccess: async () => { await refresh(); setEditing(false) } })
  const remove = useMutation({ mutationFn: () => deleteDeviceTemplate(template.id), onSuccess: refresh })
  return <Card data-testid={template.code === "ENERGY_MONITOR_12V" ? "energy-monitor-template" : undefined}><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>{template.name}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{template.code}</p></div><div className="flex flex-wrap items-center gap-2"><StatusBadge value={template.is_active ? "ACTIVE" : "DISABLED"} />{canUpdate ? <Button size="sm" variant="outline" onClick={() => setEditing((current) => !current)}><Pencil />Chỉnh sửa</Button> : null}{canDelete ? <AlertDialog><AlertDialogTrigger asChild><Button size="sm" variant="destructive"><Trash2 />Xoá</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Xoá {template.name}?</AlertDialogTitle><AlertDialogDescription>Backend sẽ từ chối nếu template còn được Device sử dụng.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Huỷ</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={() => remove.mutate()}>Xoá</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog> : null}</div></div></CardHeader><CardContent className="space-y-5">{editing ? <form className="space-y-4 rounded-xl bg-muted p-4" onSubmit={(event) => { event.preventDefault(); update.mutate() }}><TemplateFields draft={draft} onChange={setDraft} codeEditable={false} /><Button type="submit" disabled={update.isPending}>Lưu template</Button>{update.isError ? <ErrorText error={update.error} /> : null}</form> : template.description ? <p className="text-sm text-muted-foreground">{template.description}</p> : null}<div className="grid gap-5 lg:grid-cols-2"><SensorSlots template={template} models={sensorModels} canUpdate={canUpdate} refresh={refresh} /><ActuatorSlots template={template} models={actuatorModels} canUpdate={canUpdate} refresh={refresh} /></div>{remove.isError ? <ErrorText error={remove.error} /> : null}</CardContent></Card>
}

function SensorSlots({ template, models, canUpdate, refresh }: { template: DeviceTemplate; models: SensorModel[]; canUpdate: boolean; refresh: () => Promise<unknown> }) {
  const [editingId, setEditingId] = useState<number | null>(null)
  const [draft, setDraft] = useState<TemplateSensorSlotInput>({ sensor_model_id: 0, slot_code: "", sort_order: template.sensors.length, is_required: true })
  const add = useMutation({ mutationFn: () => addTemplateSensor(template.id, { ...draft, slot_code: draft.slot_code.trim().toUpperCase() }), onSuccess: async () => { await refresh(); setDraft({ sensor_model_id: 0, slot_code: "", sort_order: template.sensors.length + 1, is_required: true }) } })
  const update = useMutation({ mutationFn: ({ id, value }: { id: number; value: TemplateSensorSlotInput }) => updateTemplateSensor(template.id, id, value), onSuccess: async () => { await refresh(); setEditingId(null) } })
  const remove = useMutation({ mutationFn: (id: number) => deleteTemplateSensor(template.id, id), onSuccess: refresh })
  return <section className="space-y-3"><div className="flex items-center justify-between"><h3 className="font-semibold">Sensor slots ({template.sensors.length})</h3></div>{template.sensors.map((slot) => <SensorSlotRow key={slot.id} slot={slot} models={models} editing={editingId === slot.id} canUpdate={canUpdate} onEdit={() => setEditingId(slot.id)} onCancel={() => setEditingId(null)} onSave={(value) => update.mutate({ id: slot.id, value })} onDelete={() => remove.mutate(slot.id)} />)}{canUpdate ? <SlotForm kind="sensor" models={models} value={draft} onChange={setDraft} onSubmit={() => add.mutate()} pending={add.isPending} /> : null}{add.isError || update.isError || remove.isError ? <ErrorText error={add.error ?? update.error ?? remove.error} /> : null}</section>
}

function ActuatorSlots({ template, models, canUpdate, refresh }: { template: DeviceTemplate; models: ActuatorModel[]; canUpdate: boolean; refresh: () => Promise<unknown> }) {
  const [editingId, setEditingId] = useState<number | null>(null)
  const [draft, setDraft] = useState<TemplateActuatorSlotInput>({ actuator_model_id: 0, slot_code: "", sort_order: template.actuators.length, is_required: true })
  const add = useMutation({ mutationFn: () => addTemplateActuator(template.id, { ...draft, slot_code: draft.slot_code.trim().toUpperCase() }), onSuccess: async () => { await refresh(); setDraft({ actuator_model_id: 0, slot_code: "", sort_order: template.actuators.length + 1, is_required: true }) } })
  const update = useMutation({ mutationFn: ({ id, value }: { id: number; value: TemplateActuatorSlotInput }) => updateTemplateActuator(template.id, id, value), onSuccess: async () => { await refresh(); setEditingId(null) } })
  const remove = useMutation({ mutationFn: (id: number) => deleteTemplateActuator(template.id, id), onSuccess: refresh })
  return <section className="space-y-3"><div className="flex items-center justify-between"><h3 className="font-semibold">Actuator slots ({template.actuators.length})</h3></div>{template.actuators.map((slot) => <ActuatorSlotRow key={slot.id} slot={slot} models={models} editing={editingId === slot.id} canUpdate={canUpdate} onEdit={() => setEditingId(slot.id)} onCancel={() => setEditingId(null)} onSave={(value) => update.mutate({ id: slot.id, value })} onDelete={() => remove.mutate(slot.id)} />)}{canUpdate ? <SlotForm kind="actuator" models={models} value={draft} onChange={setDraft} onSubmit={() => add.mutate()} pending={add.isPending} /> : null}{add.isError || update.isError || remove.isError ? <ErrorText error={add.error ?? update.error ?? remove.error} /> : null}</section>
}

function SensorSlotRow({ slot, models, editing, canUpdate, onEdit, onCancel, onSave, onDelete }: { slot: TemplateSensorSlot; models: SensorModel[]; editing: boolean; canUpdate: boolean; onEdit: () => void; onCancel: () => void; onSave: (value: TemplateSensorSlotInput) => void; onDelete: () => void }) {
  const [draft, setDraft] = useState<TemplateSensorSlotInput>({ sensor_model_id: slot.sensor_model_id, slot_code: slot.slot_code, sort_order: slot.sort_order, is_required: slot.is_required })
  if (editing) return <SlotForm kind="sensor" models={models} value={draft} onChange={setDraft} onSubmit={() => onSave(draft)} onCancel={onCancel} pending={false} />
  return <SlotSummary code={slot.slot_code} model={slot.sensor_model_name} order={slot.sort_order} required={slot.is_required} canUpdate={canUpdate} onEdit={onEdit} onDelete={onDelete} />
}

function ActuatorSlotRow({ slot, models, editing, canUpdate, onEdit, onCancel, onSave, onDelete }: { slot: TemplateActuatorSlot; models: ActuatorModel[]; editing: boolean; canUpdate: boolean; onEdit: () => void; onCancel: () => void; onSave: (value: TemplateActuatorSlotInput) => void; onDelete: () => void }) {
  const [draft, setDraft] = useState<TemplateActuatorSlotInput>({ actuator_model_id: slot.actuator_model_id, slot_code: slot.slot_code, sort_order: slot.sort_order, is_required: slot.is_required })
  if (editing) return <SlotForm kind="actuator" models={models} value={draft} onChange={setDraft} onSubmit={() => onSave(draft)} onCancel={onCancel} pending={false} />
  return <SlotSummary code={slot.slot_code} model={slot.actuator_model_name} order={slot.sort_order} required={slot.is_required} canUpdate={canUpdate} onEdit={onEdit} onDelete={onDelete} />
}

function SlotSummary({ code, model, order, required, canUpdate, onEdit, onDelete }: { code: string; model: string; order: number; required: boolean; canUpdate: boolean; onEdit: () => void; onDelete: () => void }) { return <div className="flex items-center justify-between gap-3 rounded-lg border p-3"><div><p className="font-medium">{order}. {code}</p><p className="text-xs text-muted-foreground">{model} · {required ? "Bắt buộc" : "Tuỳ chọn"}</p></div>{canUpdate ? <div className="flex gap-1"><Button aria-label={`Sửa ${code}`} size="icon" variant="ghost" onClick={onEdit}><Pencil /></Button><Button aria-label={`Xoá ${code}`} size="icon" variant="ghost" onClick={onDelete}><Trash2 /></Button></div> : null}</div> }

type SlotFormProps =
  | { kind: "sensor"; models: SensorModel[]; value: TemplateSensorSlotInput; onChange: (value: TemplateSensorSlotInput) => void; onSubmit: () => void; onCancel?: () => void; pending: boolean }
  | { kind: "actuator"; models: ActuatorModel[]; value: TemplateActuatorSlotInput; onChange: (value: TemplateActuatorSlotInput) => void; onSubmit: () => void; onCancel?: () => void; pending: boolean }

function SlotForm(props: SlotFormProps) {
  if (props.kind === "sensor") {
    return <SlotFormLayout kind="sensor" models={props.models} code={props.value.slot_code} modelId={props.value.sensor_model_id} order={props.value.sort_order ?? 0} required={props.value.is_required ?? true} pending={props.pending} editing={Boolean(props.onCancel)} onCancel={props.onCancel} onSubmit={props.onSubmit} onCode={(slot_code) => props.onChange({ ...props.value, slot_code })} onModel={(sensor_model_id) => props.onChange({ ...props.value, sensor_model_id })} onOrder={(sort_order) => props.onChange({ ...props.value, sort_order })} onRequired={(is_required) => props.onChange({ ...props.value, is_required })} />
  }
  return <SlotFormLayout kind="actuator" models={props.models} code={props.value.slot_code} modelId={props.value.actuator_model_id} order={props.value.sort_order ?? 0} required={props.value.is_required ?? true} pending={props.pending} editing={Boolean(props.onCancel)} onCancel={props.onCancel} onSubmit={props.onSubmit} onCode={(slot_code) => props.onChange({ ...props.value, slot_code })} onModel={(actuator_model_id) => props.onChange({ ...props.value, actuator_model_id })} onOrder={(sort_order) => props.onChange({ ...props.value, sort_order })} onRequired={(is_required) => props.onChange({ ...props.value, is_required })} />
}

function SlotFormLayout({ kind, models, code, modelId, order, required, pending, editing, onCancel, onSubmit, onCode, onModel, onOrder, onRequired }: { kind: "sensor" | "actuator"; models: Array<SensorModel | ActuatorModel>; code: string; modelId: number; order: number; required: boolean; pending: boolean; editing: boolean; onCancel?: () => void; onSubmit: () => void; onCode: (value: string) => void; onModel: (value: number) => void; onOrder: (value: number) => void; onRequired: (value: boolean) => void }) {
  return <form className="space-y-2 rounded-lg bg-muted p-3" onSubmit={(event) => { event.preventDefault(); onSubmit() }}><Input aria-label="Slot code" placeholder="SLOT_CODE" value={code} onChange={(event) => onCode(event.target.value.toUpperCase())} required /><select aria-label="Model" className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={modelId || ""} onChange={(event) => onModel(Number(event.target.value))} required><option value="">Chọn model</option>{models.filter((model) => model.is_active).map((model) => <option key={model.id} value={model.id}>{model.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><Input aria-label="Sort order" type="number" min="0" value={order} onChange={(event) => onOrder(Number(event.target.value))} /><label className="flex items-center gap-2 text-sm"><Switch checked={required} onCheckedChange={onRequired} />Bắt buộc</label></div><div className="flex justify-end gap-2">{onCancel ? <Button type="button" size="sm" variant="ghost" onClick={onCancel}>Huỷ</Button> : null}<Button data-testid={kind === "sensor" ? "add-template-sensor" : "add-template-actuator"} type="submit" size="sm" disabled={pending || modelId <= 0}><Plus />{editing ? "Lưu" : "Thêm slot"}</Button></div></form>
}

function SensorModelCatalog({ items, loading, error, canCreate, canUpdate, canDelete }: { items: SensorModel[]; loading: boolean; error: Error | null; canCreate: boolean; canUpdate: boolean; canDelete: boolean }) {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [draft, setDraft] = useState<SensorModelInput>({ code: "", name: "", unit: "", value_type: "FLOAT", chart_type: "LINE", measurement_semantics: "GAUGE", is_active: true })
  const create = useMutation({ mutationFn: () => createSensorModel({ ...draft, code: draft.code.trim().toUpperCase(), name: draft.name.trim() }), onSuccess: async () => { await client.invalidateQueries({ queryKey: queryKeys.sensorModels }); setOpen(false) } })
  if (loading) return <Skeleton className="h-96" />; if (error) return <EmptyState icon={Database} title="Không thể tải SensorModel" description={errorMessage(error)} />
  return <div className="space-y-4">{canCreate ? <ModelCreateDialog title="Tạo SensorModel" open={open} setOpen={setOpen} pending={create.isPending} error={create.error} onSubmit={() => create.mutate()}><SensorModelFields value={draft} onChange={setDraft} codeEditable /></ModelCreateDialog> : null}<div className="grid gap-4 lg:grid-cols-2">{items.map((item) => <SensorModelCard key={item.id} item={item} canUpdate={canUpdate} canDelete={canDelete} />)}</div>{!items.length ? <EmptyState icon={Database} title="Chưa có SensorModel" description="Tạo model trước khi thêm Sensor runtime." /> : null}</div>
}

function SensorModelCard({ item, canUpdate, canDelete }: { item: SensorModel; canUpdate: boolean; canDelete: boolean }) {
  const client = useQueryClient(); const [editing, setEditing] = useState(false); const [draft, setDraft] = useState<SensorModelInput>({ code: item.code, name: item.name, unit: item.unit, description: item.description, value_type: item.value_type, chart_type: item.chart_type, measurement_semantics: item.measurement_semantics, is_active: item.is_active })
  const update = useMutation({ mutationFn: () => updateSensorModel(item.id, { name: draft.name, unit: draft.unit, description: draft.description, value_type: draft.value_type, chart_type: draft.chart_type, measurement_semantics: draft.measurement_semantics, is_active: draft.is_active }), onSuccess: async () => { await client.invalidateQueries({ queryKey: queryKeys.sensorModels }); setEditing(false) } }); const remove = useMutation({ mutationFn: () => deleteSensorModel(item.id), onSuccess: () => client.invalidateQueries({ queryKey: queryKeys.sensorModels }) })
  return <Card><CardHeader><div className="flex items-start justify-between gap-2"><div><CardTitle>{item.name}</CardTitle><p className="text-sm text-muted-foreground">{item.code} · {item.unit}</p></div><StatusBadge value={item.is_active ? "ACTIVE" : "DISABLED"} /></div></CardHeader><CardContent className="space-y-3">{editing ? <form className="space-y-3" onSubmit={(event) => { event.preventDefault(); update.mutate() }}><SensorModelFields value={draft} onChange={setDraft} codeEditable={false} /><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setEditing(false)}>Huỷ</Button><Button type="submit">Lưu</Button></div></form> : <p className="text-sm text-muted-foreground">{item.measurement_semantics} · {item.chart_type} · {item.value_type}</p>}<div className="flex gap-2">{canUpdate && !editing ? <Button size="sm" variant="outline" onClick={() => setEditing(true)}><Pencil />Sửa</Button> : null}{canDelete ? <Button size="sm" variant="ghost" onClick={() => remove.mutate()}><Trash2 />Xoá</Button> : null}</div>{update.isError || remove.isError ? <ErrorText error={update.error ?? remove.error} /> : null}</CardContent></Card>
}

function ActuatorModelCatalog({ items, loading, error, canCreate, canUpdate, canDelete }: { items: ActuatorModel[]; loading: boolean; error: Error | null; canCreate: boolean; canUpdate: boolean; canDelete: boolean }) {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [draft, setDraft] = useState<ActuatorModelInput>({ code: "", name: "", description: null, data_type: "BOOLEAN", default_state: false, sort_order: 0 })
  const create = useMutation({ mutationFn: () => createActuatorModel({ ...draft, code: draft.code.trim().toUpperCase(), name: draft.name.trim() }), onSuccess: async () => { await client.invalidateQueries({ queryKey: queryKeys.actuatorModels }); setOpen(false) } })
  if (loading) return <Skeleton className="h-96" />; if (error) return <EmptyState icon={Database} title="Không thể tải ActuatorModel" description={errorMessage(error)} />
  return <div className="space-y-4">{canCreate ? <ModelCreateDialog title="Tạo ActuatorModel" open={open} setOpen={setOpen} pending={create.isPending} error={create.error} onSubmit={() => create.mutate()}><ActuatorModelFields value={draft} onChange={setDraft} codeEditable /></ModelCreateDialog> : null}<div className="grid gap-4 lg:grid-cols-2">{items.map((item) => <ActuatorModelCard key={item.id} item={item} canUpdate={canUpdate} canDelete={canDelete} />)}</div>{!items.length ? <EmptyState icon={Database} title="Chưa có ActuatorModel" description="Tạo model trước khi thêm Actuator runtime." /> : null}</div>
}

function ActuatorModelCard({ item, canUpdate, canDelete }: { item: ActuatorModel; canUpdate: boolean; canDelete: boolean }) {
  const client = useQueryClient(); const [editing, setEditing] = useState(false); const [draft, setDraft] = useState<ActuatorModelInput>({ code: item.code, name: item.name, description: item.description, data_type: item.data_type, default_state: item.default_state, sort_order: item.sort_order })
  const update = useMutation({ mutationFn: () => updateActuatorModel(item.id, { name: draft.name, description: draft.description, data_type: draft.data_type, default_state: draft.default_state, sort_order: draft.sort_order, is_active: item.is_active }), onSuccess: async () => { await client.invalidateQueries({ queryKey: queryKeys.actuatorModels }); setEditing(false) } }); const remove = useMutation({ mutationFn: () => deleteActuatorModel(item.id), onSuccess: () => client.invalidateQueries({ queryKey: queryKeys.actuatorModels }) })
  return <Card><CardHeader><div className="flex items-start justify-between gap-2"><div><CardTitle>{item.name}</CardTitle><p className="text-sm text-muted-foreground">{item.code}</p></div><StatusBadge value={item.is_active ? "ACTIVE" : "DISABLED"} /></div></CardHeader><CardContent className="space-y-3">{editing ? <form className="space-y-3" onSubmit={(event) => { event.preventDefault(); update.mutate() }}><ActuatorModelFields value={draft} onChange={setDraft} codeEditable={false} /><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setEditing(false)}>Huỷ</Button><Button type="submit">Lưu</Button></div></form> : <p className="text-sm text-muted-foreground">{item.data_type} · mặc định {item.default_state ? "Bật" : "Tắt"} · thứ tự {item.sort_order}</p>}<div className="flex gap-2">{canUpdate && !editing ? <Button size="sm" variant="outline" onClick={() => setEditing(true)}><Pencil />Sửa</Button> : null}{canDelete ? <Button size="sm" variant="ghost" onClick={() => remove.mutate()}><Trash2 />Xoá</Button> : null}</div>{update.isError || remove.isError ? <ErrorText error={update.error ?? remove.error} /> : null}</CardContent></Card>
}

function TemplateFields({ draft, onChange, codeEditable }: { draft: DeviceTemplateInput; onChange: (value: DeviceTemplateInput) => void; codeEditable: boolean }) { return <div className="grid gap-3 sm:grid-cols-2"><TextField id={`template-code-${codeEditable}`} label="Code" value={draft.code} disabled={!codeEditable} onChange={(code) => onChange({ ...draft, code })} /><TextField id={`template-name-${codeEditable}`} label="Tên" value={draft.name} onChange={(name) => onChange({ ...draft, name })} /><div className="sm:col-span-2"><Label htmlFor={`template-description-${codeEditable}`}>Mô tả</Label><Textarea id={`template-description-${codeEditable}`} className="mt-1" value={draft.description ?? ""} onChange={(event) => onChange({ ...draft, description: event.target.value })} /></div></div> }
function SensorModelFields({ value, onChange, codeEditable }: { value: SensorModelInput; onChange: (value: SensorModelInput) => void; codeEditable: boolean }) { return <div className="grid gap-3 sm:grid-cols-2"><TextField id={`sensor-model-code-${codeEditable}`} label="Code" disabled={!codeEditable} value={value.code} onChange={(code) => onChange({ ...value, code })} /><TextField id={`sensor-model-name-${codeEditable}`} label="Tên" value={value.name} onChange={(name) => onChange({ ...value, name })} /><TextField id={`sensor-model-unit-${codeEditable}`} label="Đơn vị" value={value.unit} onChange={(unit) => onChange({ ...value, unit })} /><TextField id={`sensor-model-value-${codeEditable}`} label="Value type" value={value.value_type ?? "FLOAT"} onChange={(value_type) => onChange({ ...value, value_type })} /><TextField id={`sensor-model-chart-${codeEditable}`} label="Chart type" value={value.chart_type ?? "LINE"} onChange={(chart_type) => onChange({ ...value, chart_type })} /><TextField id={`sensor-model-semantics-${codeEditable}`} label="Measurement semantics" value={value.measurement_semantics ?? "GAUGE"} onChange={(measurement_semantics) => onChange({ ...value, measurement_semantics })} /><label className="flex items-center gap-2 text-sm"><Switch checked={value.is_active ?? true} onCheckedChange={(is_active) => onChange({ ...value, is_active })} />Đang hoạt động</label></div> }
function ActuatorModelFields({ value, onChange, codeEditable }: { value: ActuatorModelInput; onChange: (value: ActuatorModelInput) => void; codeEditable: boolean }) { return <div className="grid gap-3 sm:grid-cols-2"><TextField id={`actuator-model-code-${codeEditable}`} label="Code" disabled={!codeEditable} value={value.code} onChange={(code) => onChange({ ...value, code })} /><TextField id={`actuator-model-name-${codeEditable}`} label="Tên" value={value.name} onChange={(name) => onChange({ ...value, name })} /><TextField id={`actuator-model-type-${codeEditable}`} label="Data type" value={value.data_type ?? "BOOLEAN"} onChange={(data_type) => onChange({ ...value, data_type })} /><div><Label htmlFor={`actuator-model-order-${codeEditable}`}>Sort order</Label><Input id={`actuator-model-order-${codeEditable}`} className="mt-1" type="number" value={value.sort_order ?? 0} onChange={(event) => onChange({ ...value, sort_order: Number(event.target.value) })} /></div><label className="flex items-center gap-2 text-sm"><Switch checked={value.default_state ?? false} onCheckedChange={(default_state) => onChange({ ...value, default_state })} />Mặc định bật</label></div> }
function ModelCreateDialog({ title, open, setOpen, pending, error, onSubmit, children }: { title: string; open: boolean; setOpen: (open: boolean) => void; pending: boolean; error: Error | null; onSubmit: () => void; children: React.ReactNode }) { return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus />{title}</Button></DialogTrigger><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>Trường gửi lên tuân theo schema canonical hiện hành.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); onSubmit() }}>{children}{error ? <ErrorText error={error} /> : null}<DialogFooter><Button type="submit" disabled={pending}>Lưu</Button></DialogFooter></form></DialogContent></Dialog> }
function TextField({ id, label, value, onChange, disabled = false }: { id: string; label: string; value: string; onChange: (value: string) => void; disabled?: boolean }) { return <div><Label htmlFor={id}>{label}</Label><Input id={id} className="mt-1" value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)} required /></div> }
function ErrorText({ error }: { error: Error | null }) { return error ? <p role="alert" className="text-sm text-destructive">{errorMessage(error)}</p> : null }
